FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY ["Asoode.Shared.Abstraction/Asoode.Shared.Abstraction.csproj", "Asoode.Shared.Abstraction/"]
RUN dotnet restore "Asoode.Shared.Abstraction/Asoode.Shared.Abstraction.csproj"
COPY ["Asoode.Shared.Abstraction/", "Asoode.Shared.Abstraction/"]

COPY ["Asoode.Shared.Core/Asoode.Shared.Core.csproj", "Asoode.Shared.Core/"]
RUN dotnet restore "Asoode.Shared.Core/Asoode.Shared.Core.csproj"
COPY ["Asoode.Shared.Core/", "Asoode.Shared.Core/"]

COPY ["Asoode.Shared.Database/Asoode.Shared.Database.csproj", "Asoode.Shared.Database/"]
RUN dotnet restore "Asoode.Shared.Database/Asoode.Shared.Database.csproj"
COPY ["Asoode.Shared.Database/", "Asoode.Shared.Database/"]

COPY ["Asoode.Website.Abstraction/Asoode.Website.Abstraction.csproj", "Asoode.Website.Abstraction/"]
RUN dotnet restore "Asoode.Website.Abstraction/Asoode.Website.Abstraction.csproj"
COPY ["Asoode.Website.Abstraction/", "Asoode.Website.Abstraction/"]

COPY ["Asoode.Website.Business/Asoode.Website.Business.csproj", "Asoode.Website.Business/"]
RUN dotnet restore "Asoode.Website.Business/Asoode.Website.Business.csproj"
COPY ["Asoode.Website.Business/", "Asoode.Website.Business/"]

COPY ["Asoode.Website.Server/Asoode.Website.Server.csproj", "Asoode.Website.Server/"]
RUN dotnet restore "Asoode.Website.Server/Asoode.Website.Server.csproj"
COPY ["Asoode.Website.Server/", "Asoode.Website.Server/"]


WORKDIR "/src/Asoode.Website.Server"
RUN dotnet build "Asoode.Website.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Asoode.Website.Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "Asoode.Website.Server.dll"]
