FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY ["Asoode.Shared.Abstraction/Asoode.Shared.Abstraction.csproj", "Asoode.Shared.Abstraction/"]
RUN dotnet restore "Asoode.Shared.Abstraction/Asoode.Shared.Abstraction.csproj"
COPY ["Asoode.Shared.Abstraction/", "Asoode.Shared.Abstraction/"]

COPY ["Asoode.Shared.Core/Asoode.Shared.Core.csproj", "Asoode.Shared.Core/"]
RUN dotnet restore "Asoode.Shared.Core/Asoode.Shared.Core.csproj"
COPY ["Asoode.Shared.Core/", "Asoode.Shared.Core/"]

COPY ["Asoode.Shared.Database/Asoode.Shared.Database.csproj", "Asoode.Shared.Database/"]
RUN dotnet restore "Asoode.Shared.Database/Asoode.Shared.Database.csproj"
COPY ["Asoode.Shared.Database/", "Asoode.Shared.Database/"]

COPY ["Asoode.Workers.Abstraction/Asoode.Workers.Abstraction.csproj", "Asoode.Workers.Abstraction/"]
RUN dotnet restore "Asoode.Workers.Abstraction/Asoode.Workers.Abstraction.csproj"
COPY ["Asoode.Workers.Abstraction/", "Asoode.Workers.Abstraction/"]

COPY ["Asoode.Workers.Business/Asoode.Workers.Business.csproj", "Asoode.Workers.Business/"]
RUN dotnet restore "Asoode.Workers.Business/Asoode.Workers.Business.csproj"
COPY ["Asoode.Workers.Business/", "Asoode.Workers.Business/"]

COPY ["Asoode.Workers.Background/Asoode.Workers.Background.csproj", "Asoode.Workers.Background/"]
RUN dotnet restore "Asoode.Workers.Background/Asoode.Workers.Background.csproj"
COPY ["Asoode.Workers.Background/", "Asoode.Workers.Background/"]


WORKDIR "/src/Asoode.Workers.Background"
RUN dotnet build "Asoode.Workers.Background.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Asoode.Workers.Background.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "Asoode.Workers.Background.dll"]
