FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY ["Asoode.Shared.Abstraction/Asoode.Shared.Abstraction.csproj", "Asoode.Shared.Abstraction/"]
RUN dotnet restore "Asoode.Shared.Abstraction/Asoode.Shared.Abstraction.csproj"
COPY ["Asoode.Shared.Abstraction/", "Asoode.Shared.Abstraction/"]

COPY ["Asoode.Shared.Core/Asoode.Shared.Core.csproj", "Asoode.Shared.Core/"]
RUN dotnet restore "Asoode.Shared.Core/Asoode.Shared.Core.csproj"
COPY ["Asoode.Shared.Core/", "Asoode.Shared.Core/"]

COPY ["Asoode.Shared.Database/Asoode.Shared.Database.csproj", "Asoode.Shared.Database/"]
RUN dotnet restore "Asoode.Shared.Database/Asoode.Shared.Database.csproj"
COPY ["Asoode.Shared.Database/", "Asoode.Shared.Database/"]

COPY ["Asoode.Application.Abstraction/Asoode.Application.Abstraction.csproj", "Asoode.Application.Abstraction/"]
RUN dotnet restore "Asoode.Application.Abstraction/Asoode.Application.Abstraction.csproj"
COPY ["Asoode.Application.Abstraction/", "Asoode.Application.Abstraction/"]

COPY ["Asoode.Application.Business/Asoode.Application.Business.csproj", "Asoode.Application.Business/"]
RUN dotnet restore "Asoode.Application.Business/Asoode.Application.Business.csproj"
COPY ["Asoode.Application.Business/", "Asoode.Application.Business/"]

COPY ["Asoode.Application.Server/Asoode.Application.Server.csproj", "Asoode.Application.Server/"]
RUN dotnet restore "Asoode.Application.Server/Asoode.Application.Server.csproj"
COPY ["Asoode.Application.Server/", "Asoode.Application.Server/"]


WORKDIR "/src/Asoode.Application.Server"
RUN dotnet build "Asoode.Application.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Asoode.Application.Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "Asoode.Application.Server.dll"]
