FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["Asoode.Application.Core/Asoode.Application.Core.csproj", "Asoode.Application.Core/"]
RUN dotnet restore "Asoode.Application.Core/Asoode.Application.Core.csproj"
COPY ["Asoode.Application.Core/", "Asoode.Application.Core/"]

COPY ["Asoode.Application.Data/Asoode.Application.Data.csproj", "Asoode.Application.Data/"]
RUN dotnet restore "Asoode.Application.Data/Asoode.Application.Data.csproj"
COPY ["Asoode.Application.Data/", "Asoode.Application.Data/"]

COPY ["Asoode.Application.Business/Asoode.Application.Business.csproj", "Asoode.Application.Business/"]
RUN dotnet restore "Asoode.Application.Business/Asoode.Application.Business.csproj"
COPY ["Asoode.Application.Business/", "Asoode.Application.Business/"]

COPY ["Asoode.Servers.Background/Asoode.Servers.Background.csproj", "Asoode.Servers.Background/"]
RUN dotnet restore "Asoode.Servers.Background/Asoode.Servers.Background.csproj"
COPY ["Asoode.Servers.Background/", "Asoode.Servers.Background/"]


WORKDIR "/src/Asoode.Servers.Background"
RUN dotnet build "Asoode.Servers.Background.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Asoode.Servers.Background.csproj" -c Release -o /app/publish

FROM base AS final

ARG APP_BUILD
ARG APP_ENVIRONMENT
ARG APP_I18N_LANG
ARG APP_I18N_CULTURE
ARG APP_AUTH_ISSUER
ARG APP_AUTH_SECRET
ARG APP_AUTH_SALT
ARG APP_DB_SERVER
ARG APP_DB_PORT
ARG APP_DB_USER
ARG APP_DB_PASS
ARG APP_STORAGE_SERVER
ARG APP_STORAGE_PORT
ARG APP_STORAGE_USER
ARG APP_STORAGE_PASS
ARG APP_STORAGE_BUCKET
ARG APP_QUEUE_SERVER
ARG APP_QUEUE_PORT
ARG APP_QUEUE_USER
ARG APP_QUEUE_PASS
ARG APP_QUEUE_PREFIX
ARG APP_SMTP_SERVER
ARG APP_SMTP_PORT
ARG APP_SMTP_USER
ARG APP_SMTP_PASS
ARG APP_SMTP_SSL

ENV APP_BUILD=${APP_BUILD}
ENV APP_ENVIRONMENT=${APP_ENVIRONMENT}
ENV APP_I18N_LANG=${APP_I18N_LANG}
ENV APP_I18N_CULTURE=${APP_I18N_CULTURE}
ENV APP_AUTH_ISSUER=${APP_AUTH_ISSUER}
ENV APP_AUTH_SECRET=${APP_AUTH_SECRET}
ENV APP_AUTH_SALT=${APP_AUTH_SALT}
ENV APP_DB_SERVER=${APP_DB_SERVER}
ENV APP_DB_PORT=${APP_DB_PORT}
ENV APP_DB_USER=${APP_DB_USER}
ENV APP_DB_PASS=${APP_DB_PASS}
ENV APP_STORAGE_SERVER=${APP_STORAGE_SERVER}
ENV APP_STORAGE_PORT=${APP_STORAGE_PORT}
ENV APP_STORAGE_USER=${APP_STORAGE_USER}
ENV APP_STORAGE_PASS=${APP_STORAGE_PASS}
ENV APP_STORAGE_BUCKET=${APP_STORAGE_BUCKET}
ENV APP_QUEUE_SERVER=${APP_QUEUE_SERVER}
ENV APP_QUEUE_PORT=${APP_QUEUE_PORT}
ENV APP_QUEUE_USER=${APP_QUEUE_USER}
ENV APP_QUEUE_PASS=${APP_QUEUE_PASS}
ENV APP_QUEUE_PREFIX=${APP_QUEUE_PREFIX}
ENV APP_SMTP_SERVER=${APP_SMTP_SERVER}
ENV APP_SMTP_PORT=${APP_SMTP_PORT}
ENV APP_SMTP_USER=${APP_SMTP_USER}
ENV APP_SMTP_PASS=${APP_SMTP_PASS}
ENV APP_SMTP_SSL=${APP_SMTP_SSL}

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Asoode.Servers.Background.dll"]
