docker build \
    -t asoode-servers-background-development:1.0.0 . \
    -f ./Dockerfile-background \
    --build-arg APP_BUILD=1.0.0 \
    --build-arg APP_ENVIRONMENT=Development
    
docker build \
    -t asoode-servers-api-development:1.0.0 . \
    -f ./Dockerfile-api \
    --build-arg APP_BUILD=1.0.0 \
    --build-arg APP_ENVIRONMENT=Development
    
